defaults:
  - libero_base
  - _self_

shape_meta:
  action_dim: 7
  observation:
    rgb:
      agentview_rgb:
        - 3
        - ${task.img_height}
        - ${task.img_width}
      robot0_eye_in_hand_rgb:
        - 3
        - ${task.img_height}
        - ${task.img_width}
    depth: {}
    lowdim:
      robot0_eef_pos: 3
      robot0_gripper_qpos: 2
    pointcloud: {}
  task:
    type: vector
    dim: 512

  