defaults:
  - libero_base
  - _self_

num_pc_points: 512
shape_meta:
  action_dim: 7
  observation:
    rgb:
      agentview_rgb:
        - 3
        - ${task.img_height}
        - ${task.img_width}
      robot0_eye_in_hand_rgb:
        - 3
        - ${task.img_height}
        - ${task.img_width}
    depth:
      agentview_depth:
        - 1
        - ${task.img_height}
        - ${task.img_width}
      robot0_eye_in_hand_depth:
        - 1
        - ${task.img_height}
        - ${task.img_width}
    lowdim:
      robot0_joint_pos: 7
      robot0_eef_pos: 3
      robot0_gripper_qpos: 2
    pointcloud: 
      hand_pointcloud: 
        - ${task.num_pc_points}
        - 6
      world_pointcloud: 
        - ${task.num_pc_points}
        - 6
      agentview_pointcloud_full: 
        - ${task.img_height}
        - ${task.img_width}
        - 3
      robot0_eye_in_hand_pointcloud_full: 
        - ${task.img_height}
        - ${task.img_width}
        - 3
  task:
    type: vector
    dim: 512
  