# observation related
# seq_len: ${algo.chunk_size}
# obs_seq_len: ${algo.frame_stack}
# frame_stack: 1

suite_name: libero
benchmark_name: null
benchmark_instance:
  _target_: adapt3r.env.libero.utils.get_benchmark_instance
  benchmark_name: ${task.benchmark_name}
  distractor: ${task.distractor_objects}
  robot: ${task.robot}
mode: all
n_tasks: 10
demos_per_env: 50
distractor_objects: false
robot: Panda
camera_pose_variations: null

task_embedding_format: clip
img_height: 128
img_width: 128
shape_meta: null
horizon: 300


dataset:
  _target_: adapt3r.env.libero.utils.build_dataset
  data_prefix: ${data_prefix}
  suite_name: ${task.suite_name}
  benchmark_name: ${task.benchmark_name}
  mode: ${task.mode}
  seq_len: ${algo.dataset.seq_len}
  frame_stack: ${algo.dataset.frame_stack}
  obs_seq_len: ${algo.dataset.obs_seq_len}
  shape_meta: ${task.shape_meta}
  load_obs: ${training.load_obs}
  task_embedding_format: ${task.task_embedding_format}
  n_demos: ${task.demos_per_env}
  hdf5_cache_mode: low_dim
  load_next_obs: ${algo.dataset.load_next_obs}
  dataset_keys: ${algo.dataset.dataset_keys}

env_factory:
  _target_: adapt3r.env.libero.wrappers.LiberoWrapper
  _partial_: true 
  shape_meta: ${task.shape_meta}
  img_height: ${task.img_height}
  img_width: ${task.img_width}
  abs_action: ${algo.abs_action}
  robot: ${task.robot}
  camera_pose_variations: ${task.camera_pose_variations}
  device: ${device}

env_runner:
  _target_: adapt3r.env_runner.libero_runner.LiberoRunner
  env_factory: ${task.env_factory}
  frame_stack: ${algo.frame_stack}
  benchmark: ${task.benchmark_instance}
  mode: ${task.mode}
  rollouts_per_env: ${rollout.rollouts_per_env}
  num_parallel_envs: ${rollout.num_parallel_envs}
  max_episode_length: ${rollout.max_episode_length}
  fps: 24
  debug: false
  task_embedding_format: ${task.task_embedding_format}
  