from libero.libero.benchmark.libero_suite_task_map import libero_task_map
from copy import copy

libero_custom_task_map = {
    "libero_10_distractor": [
        "LIVING_ROOM_DISTRACTOR_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_put_both_the_cream_cheese_box_and_the_butter_in_the_basket",
        "KITCHEN_DISTRACTOR_SCENE3_turn_on_the_stove_and_put_the_moka_pot_on_it",
        "KITCHEN_DISTRACTOR_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it",
        "LIVING_ROOM_DISTRACTOR_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate",
        "STUDY_DISTRACTOR_SCENE1_pick_up_the_book_and_place_it_in_the_back_compartment_of_the_caddy",
        "LIVING_ROOM_DISTRACTOR_SCENE6_put_the_white_mug_on_the_plate_and_put_the_chocolate_pudding_to_the_right_of_the_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE1_put_both_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket",
        "KITCHEN_DISTRACTOR_SCENE8_put_both_moka_pots_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE6_put_the_yellow_and_white_mug_in_the_microwave_and_close_it",
    ],
    "libero_90_distractor": [
        "KITCHEN_DISTRACTOR_SCENE10_close_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE10_close_the_top_drawer_of_the_cabinet_and_put_the_black_bowl_on_top_of_it",
        "KITCHEN_DISTRACTOR_SCENE10_put_the_black_bowl_in_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE10_put_the_butter_at_the_back_in_the_top_drawer_of_the_cabinet_and_close_it",
        "KITCHEN_DISTRACTOR_SCENE10_put_the_butter_at_the_front_in_the_top_drawer_of_the_cabinet_and_close_it",
        "KITCHEN_DISTRACTOR_SCENE10_put_the_chocolate_pudding_in_the_top_drawer_of_the_cabinet_and_close_it",
        "KITCHEN_DISTRACTOR_SCENE1_open_the_bottom_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE1_open_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE1_open_the_top_drawer_of_the_cabinet_and_put_the_bowl_in_it",
        "KITCHEN_DISTRACTOR_SCENE1_put_the_black_bowl_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE1_put_the_black_bowl_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE2_open_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE2_put_the_black_bowl_at_the_back_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE2_put_the_black_bowl_at_the_front_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE2_put_the_black_bowl_in_the_middle_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE2_put_the_middle_black_bowl_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE2_stack_the_black_bowl_at_the_front_on_the_black_bowl_in_the_middle",
        "KITCHEN_DISTRACTOR_SCENE2_stack_the_black_bowl_in_the_middle_on_the_black_bowl_at_the_front",
        "KITCHEN_DISTRACTOR_SCENE3_put_the_frying_pan_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE3_put_the_moka_pot_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE3_turn_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE3_turn_on_the_stove_and_put_the_frying_pan_on_it",
        "KITCHEN_DISTRACTOR_SCENE4_close_the_bottom_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE4_close_the_bottom_drawer_of_the_cabinet_and_open_the_top_drawer",
        "KITCHEN_DISTRACTOR_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE4_put_the_black_bowl_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE4_put_the_wine_bottle_in_the_bottom_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE4_put_the_wine_bottle_on_the_wine_rack",
        "KITCHEN_DISTRACTOR_SCENE5_close_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE5_put_the_black_bowl_in_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE5_put_the_black_bowl_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE5_put_the_black_bowl_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE5_put_the_ketchup_in_the_top_drawer_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE6_close_the_microwave",
        "KITCHEN_DISTRACTOR_SCENE6_put_the_yellow_and_white_mug_to_the_front_of_the_white_mug",
        "KITCHEN_DISTRACTOR_SCENE7_open_the_microwave",
        "KITCHEN_DISTRACTOR_SCENE7_put_the_white_bowl_on_the_plate",
        "KITCHEN_DISTRACTOR_SCENE7_put_the_white_bowl_to_the_right_of_the_plate",
        "KITCHEN_DISTRACTOR_SCENE8_put_the_right_moka_pot_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE8_turn_off_the_stove",
        "KITCHEN_DISTRACTOR_SCENE9_put_the_frying_pan_on_the_cabinet_shelf",
        "KITCHEN_DISTRACTOR_SCENE9_put_the_frying_pan_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE9_put_the_frying_pan_under_the_cabinet_shelf",
        "KITCHEN_DISTRACTOR_SCENE9_put_the_white_bowl_on_top_of_the_cabinet",
        "KITCHEN_DISTRACTOR_SCENE9_turn_on_the_stove",
        "KITCHEN_DISTRACTOR_SCENE9_turn_on_the_stove_and_put_the_frying_pan_on_it",
        "LIVING_ROOM_DISTRACTOR_SCENE1_pick_up_the_alphabet_soup_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE1_pick_up_the_cream_cheese_box_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE1_pick_up_the_ketchup_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE1_pick_up_the_tomato_sauce_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_pick_up_the_alphabet_soup_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_pick_up_the_butter_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_pick_up_the_milk_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_pick_up_the_orange_juice_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE2_pick_up_the_tomato_sauce_and_put_it_in_the_basket",
        "LIVING_ROOM_DISTRACTOR_SCENE3_pick_up_the_alphabet_soup_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE3_pick_up_the_butter_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE3_pick_up_the_cream_cheese_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE3_pick_up_the_ketchup_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE3_pick_up_the_tomato_sauce_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE4_pick_up_the_black_bowl_on_the_left_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE4_pick_up_the_chocolate_pudding_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE4_pick_up_the_salad_dressing_and_put_it_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE4_stack_the_left_bowl_on_the_right_bowl_and_place_them_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE4_stack_the_right_bowl_on_the_left_bowl_and_place_them_in_the_tray",
        "LIVING_ROOM_DISTRACTOR_SCENE5_put_the_red_mug_on_the_left_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE5_put_the_red_mug_on_the_right_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE5_put_the_white_mug_on_the_left_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE5_put_the_yellow_and_white_mug_on_the_right_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE6_put_the_chocolate_pudding_to_the_left_of_the_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE6_put_the_chocolate_pudding_to_the_right_of_the_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE6_put_the_red_mug_on_the_plate",
        "LIVING_ROOM_DISTRACTOR_SCENE6_put_the_white_mug_on_the_plate",
        "STUDY_DISTRACTOR_SCENE1_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE1_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE1_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE1_pick_up_the_yellow_and_white_mug_and_place_it_to_the_right_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE2_pick_up_the_book_and_place_it_in_the_back_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE2_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE2_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE2_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE3_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE3_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE3_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE3_pick_up_the_red_mug_and_place_it_to_the_right_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE3_pick_up_the_white_mug_and_place_it_to_the_right_compartment_of_the_caddy",
        "STUDY_DISTRACTOR_SCENE4_pick_up_the_book_in_the_middle_and_place_it_on_the_cabinet_shelf",
        "STUDY_DISTRACTOR_SCENE4_pick_up_the_book_on_the_left_and_place_it_on_top_of_the_shelf",
        "STUDY_DISTRACTOR_SCENE4_pick_up_the_book_on_the_right_and_place_it_on_the_cabinet_shelf",
        "STUDY_DISTRACTOR_SCENE4_pick_up_the_book_on_the_right_and_place_it_under_the_cabinet_shelf",
    ],
    "libero_10_sawyer": copy(libero_task_map['libero_10']),
    "libero_90_sawyer": copy(libero_task_map['libero_90']),
    "libero_10_ur5e": copy(libero_task_map['libero_10']),
    "libero_90_ur5e": copy(libero_task_map['libero_90']),
    "libero_10_kinova3": copy(libero_task_map['libero_10']),
    "libero_90_kinova3": copy(libero_task_map['libero_90']),
    "libero_10_iiwa": copy(libero_task_map['libero_10']),
    "libero_90_iiwa": copy(libero_task_map['libero_90']),
}
