defaults:
  - task: metaworld_ml45
  - algo: quest
  - _self_

exp_name: debug # 
variant_name: null
seed: 10000
device: cuda:0
output_prefix: ./experiments
data_prefix: ./data
make_unique_experiment_dir: false
logging_folder: training

checkpoint_path: null


train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: true
  num_workers: 4
  persistent_workers: true
  pin_memory: true
  multiprocessing_context: fork

training:
  # training
  normalize_action: true
  normalize_obs: false
  n_epochs: 100
  grad_clip: 100.
  save_interval: 10
  log_interval: 100
  use_amp: false
  use_tqdm: false
  do_profile: false
  save_all_checkpoints: true
  load_obs: true
  cut: 0

  # resume training
  resume: true
  resume_path: ""

rollout:
  enabled: true
  interval: 25
  rollouts_per_env: 1
  max_episode_length: ${task.horizon}
  n_video: 0
  num_parallel_envs: 1


logging:
  group: null
  mode: online # set logging.mode=disabled to disable wandb
  project: adapt3r
  resume: true
  save_code: true




