defaults:
  - chunk_base
  - _self_

policy:
  _target_: adapt3r.algos.baku.Baku
  hidden_dim: 256
  std: 0.1
  frame_stack: ${algo.frame_stack}
  embed_dim: ${algo.embed_dim}
  policy_head: deterministic


name: baku

lr: 0.0001
weight_decay: 0.0001

embed_dim: 256
action_horizon: 2

chunk_size: 16 # this is output action sequence length
frame_stack: 1 # this is input observation sequence length

dataset:
  seq_len: ${algo.chunk_size}
  frame_stack: ${algo.frame_stack}
  obs_seq_len: 1
  lowdim_obs_seq_len: null
  load_obs_for_pretrain: true
  load_next_obs: false
