defaults:
  - encoder: rgb
  - aug: image

name: ${eval:'${algo.name}'} # this is used to override the name of the algo

embed_dim: 512
lowdim_embed_dim: ${algo.embed_dim}
image_embed_dim: ${algo.embed_dim}
lang_embed_dim: ${algo.embed_dim}
abs_action: false
frame_stack: 1
eecf: false
batch_size: 64

lr: 1.0e-4
weight_decay: 1.0e-6

policy:
  encoder: ${algo.encoder}
  normalizer: 
    _target_: adapt3r.algos.utils.normalizer.Normalizer
    mode: limits
    output_min: -1
    output_max: 1
  aug_factory: ${algo.aug}
  optimizer_factory:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: ${algo.lr}
    betas: [0.95, 0.999]
    eps: 1.0e-8
    weight_decay: ${algo.weight_decay}
  abs_action: ${algo.abs_action}
  shape_meta: ${task.shape_meta}
  eecf: ${algo.eecf}
  bimanual: ${task.bimanual}
  device: ${device}

scheduler_kwargs:
  schedule_type: cosine
  warmup_steps: 1000
  lr: ${algo.lr}
  end_factor: 0.01

dataset:
  seq_len: 1
  frame_stack: 1
  obs_seq_len: 1
  lowdim_obs_seq_len: null
  load_next_obs: false
  # dataset_keys: [actions, abs_actions]
  