defaults:
  - chunk_base
  - _self_

policy:
  _target_: adapt3r.algos.diffusion_policy.DiffusionPolicy
  diffusion_model_factory:
    _target_: adapt3r.algos.diffusion_policy.DiffusionModel
    _partial_: true
    noise_scheduler: 
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: ${algo.diffusion_train_steps}
      beta_schedule: squaredcos_cap_v2
    global_cond_dim: ${eval:'${algo.embed_dim} + ${algo.lang_emb_dim}'}
    diffusion_step_emb_dim: ${algo.diffusion_step_emb_dim}
    down_dims: [256,512,1024]
    ema_power: 0.75
    chunk_size: ${algo.chunk_size}
    diffusion_inf_steps: ${algo.diffusion_inf_steps}
    device: ${device}
  embed_dim: ${algo.embed_dim}
  device: ${device}


name: diffusion_policy

lr: 0.0001
weight_decay: 0.0001

lowdim_embed_dim: 128
image_embed_dim: ${algo.embed_dim} 
pc_embed_dim: ${algo.embed_dim}
diffusion_step_emb_dim: ${algo.embed_dim}
lang_emb_dim: ${algo.embed_dim} # clip embedding size
embed_dim: 256

chunk_size: 16 # this is input sequence length to encoder


diffusion_train_steps: 100
diffusion_inf_steps: 10

action_horizon: 2 # mpc horizon for execution

frame_stack: 1

dataset:
  seq_len: ${algo.chunk_size}
  frame_stack: ${algo.frame_stack}
  obs_seq_len: 1
  lowdim_obs_seq_len: null
  load_obs_for_pretrain: true
  load_next_obs: false


